export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const ADD_ASSET = 'ADD_ASSET';
export const REMOVE_ASSET = 'REMOVE_ASSET';
export const UPDATE_ASSET_PRICE = 'UPDATE_ASSET_PRICE';
export const UPDATE_ASSET_STATE = 'UPDATE_ASSET_STATE';
