export const FIAT_CALL_REQUEST = 'FIAT_CALL_REQUEST';
export const FIAT_CALL_SUCCESS = 'FIAT_CALL_SUCCESS';
export const FIAT_CALL_FAILURE = 'FIAT_CALL_FAILURE';
export const SET_CURRENCY = 'SET_CURRENCY';
export const UPDATE_DOMAIN = 'UPDATE_DOMAIN';
export const TOGGLE_BALANCE = 'TOGGLE_BALANCE';
